#ifndef PARSER_TYPES_H
#define PARSER_TYPES_H

// Minimal type definitions for the parser and lexer
// This file provides forward declarations and token definitions

#include <string>
#include <vector>

// Forward declarations - actual types defined in ast.h
class ASTNode;
class ParamNode;
class DeclNode;
class StmtNode;
class ExprNode;
class ProgramNode;
class FuncDeclNode;
class StructTypeNode;
class StructFieldNode;
class MethodDeclNode;
class VarDeclNode;
class ForStmtNode;
class ReturnStmtNode;
class CompoundStmtNode;
class NumberNode;
class StringNode;
class IdentifierNode;
class BinaryOpNode;
class UnaryOpNode;
class AssignNode;
class TypeBodyNode;
class InterfaceTypeNode;
class InterfaceMethodNode;
class MemberCallNode;
class QualifiedCallNode;
class CallNode;
class IndexNode;
class CompoundAssignNode;
class IfStmtNode;
class TupleExprNode;
class TupleVarDeclNode;
class TupleAssignStmtNode;
class ForRangeStmtNode;
class ContinueStmtNode;
class InitListExprNode;

// Token definitions from bison
// These must match the values in parser.c (generated by bison)
#define IDENTIFIER 258
#define NUMBER 259
#define FUN 260
#define VAR 261
#define REF 262
#define RETURN 263
#define FOR 264
#define IF 265
#define ELSE 266
#define CONTINUE 267
#define LE 268
#define GE 269
#define EQ 270
#define NE 271
#define AND 272
#define OR 273
#define INC 274
#define DEC 275
#define PLUS_EQ 276
#define MINUS_EQ 277
#define STAR_EQ 278
#define SLASH_EQ 279
#define TYPE 280
#define STRUCT 281
#define STRING_TYPE 282
#define INTERFACE 283
#define COLONCOLON 284
#define ARROW 285
#define STRING_LITERAL 286

#endif  // PARSER_TYPES_H